apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockpit-app-pv-claim
  labels:
    app: cockpit-kubernetes
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
