apiVersion: v1
kind: Service
metadata:
  name: cockpit
  labels:
    app: cockpit-kubernetes
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: cockpit-kubernetes
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cockpit
  labels:
    app: cockpit-kubernetes
    tier: frontend
spec:
  selector:
    matchLabels:
      app: cockpit-kubernetes
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cockpit-kubernetes
        tier: frontend
    spec:
      containers:
      - image: pavanpaik/cockpit:1.6
        name: cockpit
        ports:
        - containerPort: 80
          name: cockpit
        env:
        - name: COCKPIT_SESSION_NAME
          value: cockpit
        - name: COCKPIT_SALT
          value: 2FA36319-6071-4C71-B565-AB825D448D70
        - name: COCKPIT_DATABASE_SERVER
          value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017
        - name: COCKPIT_DATABASE_RS_NAME
          value: rs0
        - name: COCKPIT_DATABASE_NAME
          value: cockpit_master
        volumeMounts:
        - name: cockpit-app-persistent-storage
          mountPath: /var/www/html/storage
      volumes:
      - name: cockpit-app-persistent-storage
        persistentVolumeClaim:
          claimName: cockpit-app-pv-claim


