apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    app: cockpit-kubernetes
    tier: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    name: mongo
    app: cockpit-kubernetes
    tier: backend
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: prod
        app: cockpit-kubernetes
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=prod"
              
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      labels:
        app: cockpit-kubernetes
        tier: backend
    spec:
      accessModes: 
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 2Gi